### ISSUE TITLE
Provide GraphQL Endpoint and instructions for obtaining Spanish version of content

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#14]
As a systems architect, I have documented the GraphQL query and data response, highlighting the specific fields/mechanism to identify the Spanish version so that engineers know how spanish content can be consumed by the build process/front end.

**Acceptance Criteria:**

- Added to Volume II is:
- [x] A screenshot of the graphQL output highlighting the key for Spanish content 
- [x] Instructions for querying GraphQL and obtaining Spanish content

**Comment by ElijahLynn** [comment]
We just discussed these 3 items for the AC "Instructions for querying GraphQL and obtaining Spanish content":

1. Single node example (easy to absorb) - https://benefits.va.gov/BENEFITS/espanol/pension_veteran.asp
2. Multiple node example (shows we can adapt to existing process easily)
3. Highlight that this can be adapted to existing FE build process easily by updating the *.graphql.js files where needed (Ask Jeff if desireable to be specific here)

**Comment by aurora-a-k-a-lightning** [comment]
Working in progress query for translated pages
```
query GetSpanishTranslatedPages {
  nodeQuery(limit: 2000, 
    filter: {
      conditions: 
      [
        {
          field: "type", 
          value: ["page"]
        }
      ]
    }) 
  {
    entities {
      ... on NodePage {
        title
        entityId
        entityType
        entityBundle
        entityLabel
        entityTranslation(language: ES) {
          ...on NodePage {
            title
          }
          entityLanguage {
            name
          }
        }
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/19178435/68982513-21c49980-07bc-11ea-8a28-05f699cf8489.png)

**Comment by aurora-a-k-a-lightning** [comment]
with the url path
```
query GetSpanishTranslatedPages {
  nodeQuery(limit: 2000, 
    filter: {
      conditions: 
      [
        {
          field: "type", 
          value: ["page"]
        }
      ]
    }) 
  {
    entities {
      ... on NodePage {
        entityBundle
        entityId
        entityPublished
        title
        entityUrl {
          ... on EntityCanonicalUrl {
            breadcrumb {
              url {
                path
                routed
              }
              text
            }
            path
          }
        }
        entityMetatags {
          __typename
          key
          value
        }
        title
        entityTranslation(language: ES) {
          ...on NodePage {
            title
            entityUrl {
              ... on EntityCanonicalUrl {
                breadcrumb {
                  url {
                    path
                    routed
                  }
                  text
                }
                path
              }
            }
          }
          entityLanguage {
            name
          }
        }
      }
    }
  }
}

```

**Comment by aurora-a-k-a-lightning** [comment]
with the spanish menu
```
query GetSpanishTranslatedPages {
  nodeQuery(limit: 2000, filter: {conditions: [{field: "type", value: ["page"]}]}) {
    entities {
      ... on NodePage {
        entityBundle
        entityId
        entityPublished
        title
        entityUrl {
          ... on EntityCanonicalUrl {
            breadcrumb {
              url {
                path
                routed
              }
              text
            }
            path
          }
        }
        entityMetatags {
          __typename
          key
          value
        }
        title
        entityTranslation(language: ES) {
          ... on NodePage {
            title
            entityUrl {
              ... on EntityCanonicalUrl {
                breadcrumb {
                  url {
                    path
                    routed
                  }
                  text
                }
                path
              }
            }
          }
          entityLanguage {
            name
          }
        }
      }
    }
  }
  menuByName(name: "pension-benefits-hub") {
    name
    description
    links {
      label
      expanded
      description
      url {
        path
      }
      links {
        label
        expanded
        description
        url {
          path
        }
        links {
          label
          expanded
          description
          url {
            path
          }
          links {
            label
            expanded
            description
            url {
              path
            }
            links {
              label
              expanded
              description
              url {
                path
              }
              links {
                label
                expanded
                description
                url {
                  path
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by ElijahLynn** [comment]
Alrighty, with the help of @meyerweb's `[dencoder](https://meyerweb.com/eric/tools/dencoder/)` tool (thank you Eric!), I was able to encode the GraphQL queries into a shareable URL. 

Here is the [URL](http://rfq.va.agile6.com/graphql/explorer?variables=%7B%0A%20%20%22langcode%22%3A%20%22ES%22%2C%0A%20%20%22nid%22%3A%20%22585%22%0A%7D&query=fragment%20qa%20on%20ParagraphQA%20%7B%0A%20%20parentFieldName%0A%20%20entityId%0A%20%20entityBundle%0A%20%20fieldQuestion%0A%20%20fieldAnswer%20%7B%0A%20%20%20%20entity%20%7B%0A%20%20%20%20%20%20entityTranslation(language%3A%20%24langcode)%20%7B%0A%20%20%20%20%20%20%20%20...wysiwyg%0A%20%20%20%20%20%20%20%20...process%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0Afragment%20wysiwyg%20on%20ParagraphWysiwyg%20%7B%0A%20%20fieldWysiwyg%20%7B%0A%20%20%20%20processed%0A%20%20%7D%0A%7D%0Afragment%20process%20on%20ParagraphProcess%20%7B%0A%20%20fieldSteps%20%7B%0A%20%20%20%20processed%0A%20%20%7D%0A%7D%0A%0Aquery%20GetSpanishTranslatedPage(%24nid%3A%20%5BString%5D%2C%20%24langcode%3A%20LanguageId!)%20%7B%0A%20%20nodeQuery(filter%3A%20%7Bconditions%3A%20%5B%7Bfield%3A%20%22nid%22%2C%20value%3A%20%24nid%7D%5D%7D)%20%7B%0A%20%20%20%20entities%20%7B%0A%20%20%20%20%20%20...%20on%20NodePage%20%7B%0A%20%20%20%20%20%20%20%20entityTranslation(language%3A%20%24langcode)%20%7B%0A%20%20%20%20%20%20%20%20%20%20entityLanguage%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20entityBundle%0A%20%20%20%20%20%20%20%20%20%20entityId%0A%20%20%20%20%20%20%20%20%20%20entityUrl%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20EntityCanonicalUrl%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20...%20on%20NodePage%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20fieldIntroText%0A%20%20%20%20%20%20%20%20%20%20%20%20fieldFeaturedContent%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20entity%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20entityType%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20entityBundle%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20entityTranslation(language%3A%20%24langcode)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...qa%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) to query the ES/Spanish version of node 585, with adjustable variables to change the language and node ID. 

And here is the [URL](http://rfq.va.agile6.com/graphql/explorer?query=%7B%0A%20%20menuByName(name%3A%20%22pension-benefits-hub%22%2C%20language%3A%20ES)%20%7B%0A%20%20%20%20name%0A%20%20%20%20description%0A%20%20%20%20links%20%7B%0A%20%20%20%20%20%20label%0A%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20links%20%7B%0A%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20links%20%7B%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20links%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20links%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20links%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20expanded%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) to query the sidebar menu in ES/Spanish. 

p.s. This is a workable solution to not having a "share link to query" button in the Graphiql Explorer UI right now https://github.com/graphql/graphiql/issues/1003.
