### ISSUE TITLE
Graphical Mock to show how a user would get from one piece of content to another.

### ISSUE THREAD

**Issue by swirtSJW** [agilesix/va.gov-cms#15]
As a site user it would be nice to have a link / button to be able to toggle between various translations of the content. 

This would be on the front end so the full implementation is not needed, but it would be nice to set out an example of the what it might look like.

**Comment by kevwalsh** [comment]
This may exist already in a public VA repo, i'll poke around.

**Comment by kevwalsh** [comment]
I found a link to a design in some [spanish-speaking vet user research sessions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/spanish-translation/research/notes) that were done back in May

[Here's a link to the prototype in Invision](https://vsateams.invisionapp.com/share/JNRWYURRY5Q#/screens/362227910)

And a screenshot of the language switcher
![VHA-Translation-Home_Loans-Eligibility-SPA](https://user-images.githubusercontent.com/643678/68914068-4d4b7380-072b-11ea-9821-6c05fd813c7b.jpg)
