### ISSUE TITLE
User gets error "Cannot translate original content" when editing a non-translatable paragraph

### ISSUE THREAD

**Issue by bderfer68** [agilesix/va.gov-cms#32]
Steps to reproduce: 
- Create or navigate to a translated page.
- Edit a paragraph field that is not translatable. 
- Click "Save."

Actual Result:
- User receives the error "Cannot translate original content."

Expected Result: 
- User should not be allowed to edit a non-translatable field.

![Screen Shot 2019-11-15 at 2 27 23 PM](https://user-images.githubusercontent.com/8270204/68980033-1d947e00-07b4-11ea-8f83-576e1eab0d98.png)

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/paragraphs/issues/2956311#comment-12820064   references this issue and points to directions here https://www.drupal.org/node/2735121

**Comment by swirtSJW** [comment]
The solution is in a PR.
