### ISSUE TITLE
Replace Translate link with translate button on /admin/content

### ISSUE THREAD

**Issue by kevwalsh** [agilesix/va.gov-cms#37]
As a content manager looking at the list of content, i want an easy to access Translate link that stands out visually. 

Acceptance Criteria:

1. The Translate link on the content dashboard should be a button for English version

1. The translate link should say, "Manage translations" for any translated language version

## Testing steps
- [x] Visit /admin/content as an editor.   Validate that the translate button exists on rows for content of type "Benefits detail page".
- [x] click the translate button and validate that it takes you to the "Translate" tab for that node.  example: /node/586/translations

**Comment by swirtSJW** [comment]
This is included with this PR https://github.com/agilesix/va.gov-cms/pull/44

**Comment by swirtSJW** [comment]
Decisions made:  

- The button should say "Translate"  because it is a verb and "Manage Translations" leads to a button that is much too large for the interface.

![image](https://user-images.githubusercontent.com/5752113/69097929-94847d80-0a25-11ea-9d78-da775c9b737d.png)
