### ISSUE TITLE
Add training documentation to Drupal

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#52]
Add https://docs.google.com/document/d/1wK-jfVSiueDkZcQ9V-2LPX1rq2rTySELUeyKeuzZgrg/edit#

to Github readme  https://github.com/agilesix/va.gov-cms/tree/multilingual-tech-demo/READMES

**Comment by kevwalsh** [comment]
Documentation can be found at http://rfq.va.agile6.com/documentation/spanish-translation

**Comment by kevwalsh** [comment]
QA'd by Howard Brande, and iteration made.
