### ISSUE TITLE
Set up bundles and fields for translation for Eligibility page

### ISSUE THREAD

**Issue by kevwalsh** [agilesix/va.gov-cms#6]
AC
* All bundles and fields identified by multilingual content model defined in #5 can be translated by an admin user (other permissions will be added later)
* The /admin/content screen has been updated to show the language of each node

Testing
- [ ] from /admin/content, search for "pension eligibility"
- [ ] Edit OR view the content, and click the translate tab.
- [ ] Edit all fields that have editable English content in them (eg, don't edit entity reference fields like Owner). you can test by prepending "Español" to the text of each field. Don't bother changing the URL alias field. 
- [ ] Save and publish. 
- [ ] You should be taken to /es/pension/eligibility
- [ ] You should see your Spanish content 
- [ ] Click on the translate tab again, you should see the status of the two translations.

**Comment by swirtSJW** [comment]
Merged but needs to be fully QA'd Will do that in the morning.
